### ISSUE TITLE
hi,can u give some demo to run your model

### ISSUE THREAD

**Issue by anthonyyuan** [pi-null-mezon/FaceAntiSpoofing#1]
ｉ　do not run your demo. can give example .how do  i use your mode

**Comment by pi-null-mezon** [comment]
Hello. Model by itself can be found [here](https://github.com/pi-null-mezon/FaceAntiSpoofing/tree/master/ReplayAttack/Models).

How to run? It is not an object of this repo. So, you need to learn of "how to work with Dlib dnn module?" somwhere else.
